### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by No9** [rescrv/HyperLevelDB#18]
Hi All 
Over at leveldown-hyper we are looking to confirm that you don't currently support windows.
https://github.com/Level/leveldown-hyper/issues/15

If that's the case do you have plans to support windows or do you have any pointers on where there might be some gotchas
Thanks

**Comment by ralphtheninja** [comment]
:+1:

**Comment by el33th4x0r** [comment]
Windows support is not on our short or medium-term roadmap. We'd be very
happy to work with contributors to incorporate your modifications on this
front though.

**Comment by ren85** [comment]
I've made an attempt to port hyperleveldb to Windows. https://github.com/ren85/hyperleveldb_windows
It's not finished, but perhaps would be a good starting point for someone better-skilled.
